matrix:
  include:
    - ARCH: amd64
      STAGE: build
    - ARCH: arm
      STAGE: build
    - ARCH: amd64
      STAGE: deploy

platform: linux/${ARCH}

pipeline:
  publish:
    image: justinbarrick/docker:latest
    secrets: [ DOCKER_USERNAME, DOCKER_PASSWORD ]
    repo: justinbarrick/drone-manifest
    tags:
    - ${ARCH}-latest
    - ${ARCH}-${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:7}
    - ${ARCH}
    privileged: true
    when:
      branch: master
      matrix:
        STAGE: build

  manifest:
    image: justinbarrick/drone-manifest:test
    secrets: [ DOCKER_USERNAME, DOCKER_PASSWORD ]
    repo: justinbarrick/drone-manifest
    tag: latest
    images:
      - repo: justinbarrick/drone-manifest
        tag: arm
        annotations:
          arch: arm
      - repo: justinbarrick/drone-manifest
        tag: amd64
        annotations:
          arch: amd64
    privileged: true
    when:
      branch: master
      matrix:
        STAGE: deploy
